Add `editorial_summary` to atmosphere fields
googlemaps/google-maps-services-python pull request #472
Opened 2023-01-15 04:45 UTC by jloffredo2

Fixes #471 🦕

2023-01-15 04:47 UTC, jloffredo2 commented
CLA has been signed

2023-01-24 09:00 UTC, wangela requested changes
Thank you for your pull request. Please revert the change to `PLACES_FIND_FIELDS_ATMOSPHERE` and we'll be good to go. 

Noting here that it would be inadvisable to add this field to `tests/test_places.py` since the editorial summary content might change.

2023-01-24 09:00 UTC, wangela commented on googlemaps/places.py
> +PLACES_FIND_FIELDS_ATMOSPHERE = {"editorial_summary","price_level", "rating", "user_ratings_total"}
`editorial_summary` is not supported for Find Place. See [documentation](https://developers.google.com/maps/documentation/places/web-service/place-data-fields#places-api-fields-support).

2023-01-24 17:52 UTC, jloffredo2 commented
@wangela As per your request, I have reverted the change to `PLACES_FIND_FIELDS_ATMOSPHERE` and have added `feat:` to this PR title.

2023-01-24 19:05 UTC, wangela approved these changes
Thanks for incorporating the feedback!

2023-01-24 19:12 UTC, merged